require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/anchor_rates", type: :request do
  # AnchorRate requires admin or material_buyer role for create/update/destroy
  let(:admin_user) { create(:user, :admin) }
  let(:material_buyer) { create(:user, role: 'material_buyer') }
  let(:regular_user) { create(:user) }

  # This should return the minimal set of attributes required to create a valid
  # AnchorRate. As you add validations to AnchorRate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Anchor A", waste_percentage: 5.0, material_cost: 100.0 }
  }

  let(:invalid_attributes) {
    { name: "", waste_percentage: -1.0, material_cost: -1.0 }
  }

  before { sign_in(admin_user) }

  describe "PATCH /reorder" do
    it "reorders the anchors" do
      a1 = AnchorRate.create!(name: "A1", waste_percentage: 5, material_cost: 10, position: 1)
      a2 = AnchorRate.create!(name: "A2", waste_percentage: 5, material_cost: 10, position: 2)
      
      patch reorder_anchor_rates_path, params: { ids: [a2.id, a1.id] }
      
      expect(response).to have_http_status(:ok)
      expect(a2.reload.position).to eq(1)
      expect(a1.reload.position).to eq(2)
    end
  end

  describe "GET /index" do
    it "renders a successful response" do
      AnchorRate.create! valid_attributes
      get anchor_rates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      anchor_rate = AnchorRate.create! valid_attributes
      get anchor_rate_url(anchor_rate)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_anchor_rate_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      anchor_rate = AnchorRate.create! valid_attributes
      get edit_anchor_rate_url(anchor_rate)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnchorRate" do
        expect {
          post anchor_rates_url, params: { anchor_rate: valid_attributes }
        }.to change(AnchorRate, :count).by(1)
      end

      it "redirects to the created anchor_rate" do
        post anchor_rates_url, params: { anchor_rate: valid_attributes }
        expect(response).to redirect_to(anchor_rate_url(AnchorRate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnchorRate" do
        expect {
          post anchor_rates_url, params: { anchor_rate: invalid_attributes }
        }.to change(AnchorRate, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post anchor_rates_url, params: { anchor_rate: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "Updated Anchor" }
      }

      it "updates the requested anchor_rate" do
        anchor_rate = AnchorRate.create! valid_attributes
        patch anchor_rate_url(anchor_rate), params: { anchor_rate: new_attributes }
        anchor_rate.reload
        expect(anchor_rate.name).to eq("Updated Anchor")
      end

      it "redirects to the anchor_rate" do
        anchor_rate = AnchorRate.create! valid_attributes
        patch anchor_rate_url(anchor_rate), params: { anchor_rate: new_attributes }
        anchor_rate.reload
        expect(response).to redirect_to(anchor_rate_url(anchor_rate))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        anchor_rate = AnchorRate.create! valid_attributes
        patch anchor_rate_url(anchor_rate), params: { anchor_rate: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested anchor_rate" do
      anchor_rate = AnchorRate.create! valid_attributes
      expect {
        delete anchor_rate_url(anchor_rate)
      }.to change(AnchorRate, :count).by(-1)
    end

    it "redirects to the anchor_rates list" do
      anchor_rate = AnchorRate.create! valid_attributes
      delete anchor_rate_url(anchor_rate)
      expect(response).to redirect_to(anchor_rates_url)
    end
  end
end
