require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/clients", type: :request do
  let(:user) { create(:user) }
  
  # This should return the minimal set of attributes required to create a valid
  # Client. As you add validations to Client, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:client)
  }

  let(:invalid_attributes) {
    { business_name: "" } # Client has no validations, but we can test with empty if needed
  }

  before { sign_in(user) }

  describe "GET /contacts" do
    it "returns a successful JSON response with contacts" do
      client = Client.create! valid_attributes
      contact = create(:contact, client: client)
      
      get contacts_client_url(client, format: :json)
      
      expect(response).to be_successful
      expect(response.content_type).to match(/application\/json/)
      
      json_response = JSON.parse(response.body)
      expect(json_response.first["id"]).to eq(contact.id)
      expect(json_response.first["name"]).to eq(contact.name)
    end
  end

  describe "GET /index" do
    it "renders a successful response" do
      Client.create! valid_attributes
      get clients_url
      expect(response).to be_successful
    end

    it "orders clients alphabetically by business_name" do
      Client.delete_all
      create(:client, business_name: "Zebra Corp")
      create(:client, business_name: "Apple Inc")
      create(:client, business_name: "Middle Co")

      get clients_url
      
      # We check the order of the clients assigned to the view
      expect(controller.view_assigns["clients"].map(&:business_name)).to eq(["Apple Inc", "Middle Co", "Zebra Corp"])
    end

    it "orders JSON results alphabetically by business_name" do
      Client.delete_all
      create(:client, business_name: "Zebra Corp")
      create(:client, business_name: "Apple Inc")

      get clients_url(format: :json)
      
      json_response = JSON.parse(response.body)
      expect(json_response.map { |c| c["text"] }).to eq(["Apple Inc", "Zebra Corp"])
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      client = Client.create! valid_attributes
      get client_url(client)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_client_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      client = Client.create! valid_attributes
      get edit_client_url(client)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Client" do
        expect {
          post clients_url, params: { client: valid_attributes }
        }.to change(Client, :count).by(1)
      end

      it "redirects to the created client" do
        post clients_url, params: { client: valid_attributes }
        expect(response).to redirect_to(client_url(Client.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Client" do
        expect {
          post clients_url, params: { client: invalid_attributes }
        }.to change(Client, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post clients_url, params: { client: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { business_name: "Updated Name" }
      }

      it "updates the requested client" do
        client = Client.create! valid_attributes
        patch client_url(client), params: { client: new_attributes }
        client.reload
        expect(client.business_name).to eq("Updated Name")
      end

      it "redirects to the client" do
        client = Client.create! valid_attributes
        patch client_url(client), params: { client: new_attributes }
        client.reload
        expect(response).to redirect_to(client_url(client))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        client = Client.create! valid_attributes
        patch client_url(client), params: { client: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    let(:admin) { create(:user, :admin) }
    before { sign_in(admin) }

    it "destroys the requested client" do
      client = Client.create! valid_attributes
      expect {
        delete client_url(client)
      }.to change(Client, :count).by(-1)
    end

    it "redirects to the clients list" do
      client = Client.create! valid_attributes
      delete client_url(client)
      expect(response).to redirect_to(clients_url)
    end
  end
end
