require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/crane_rates", type: :request do
  let(:user) { create(:user) }
  
  # This should return the minimal set of attributes required to create a valid
  # CraneRate. As you add validations to CraneRate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  before { sign_in(user) }

  describe "GET /index" do
    it "renders a successful response" do
      CraneRate.create! valid_attributes
      get crane_rates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      crane_rate = CraneRate.create! valid_attributes
      get crane_rate_url(crane_rate)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_crane_rate_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      crane_rate = CraneRate.create! valid_attributes
      get edit_crane_rate_url(crane_rate)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CraneRate" do
        expect {
          post crane_rates_url, params: { crane_rate: valid_attributes }
        }.to change(CraneRate, :count).by(1)
      end

      it "redirects to the created crane_rate" do
        post crane_rates_url, params: { crane_rate: valid_attributes }
        expect(response).to redirect_to(crane_rate_url(CraneRate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CraneRate" do
        expect {
          post crane_rates_url, params: { crane_rate: invalid_attributes }
        }.to change(CraneRate, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post crane_rates_url, params: { crane_rate: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested crane_rate" do
        crane_rate = CraneRate.create! valid_attributes
        patch crane_rate_url(crane_rate), params: { crane_rate: new_attributes }
        crane_rate.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the crane_rate" do
        crane_rate = CraneRate.create! valid_attributes
        patch crane_rate_url(crane_rate), params: { crane_rate: new_attributes }
        crane_rate.reload
        expect(response).to redirect_to(crane_rate_url(crane_rate))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        crane_rate = CraneRate.create! valid_attributes
        patch crane_rate_url(crane_rate), params: { crane_rate: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested crane_rate" do
      crane_rate = CraneRate.create! valid_attributes
      expect {
        delete crane_rate_url(crane_rate)
      }.to change(CraneRate, :count).by(-1)
    end

    it "redirects to the crane_rates list" do
      crane_rate = CraneRate.create! valid_attributes
      delete crane_rate_url(crane_rate)
      expect(response).to redirect_to(crane_rates_url)
    end
  end
end
