require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/crane_complements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CraneComplement. As you add validations to CraneComplement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CraneComplement.create! valid_attributes
      get crane_complements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      crane_complement = CraneComplement.create! valid_attributes
      get crane_complement_url(crane_complement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_crane_complement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      crane_complement = CraneComplement.create! valid_attributes
      get edit_crane_complement_url(crane_complement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CraneComplement" do
        expect {
          post crane_complements_url, params: { crane_complement: valid_attributes }
        }.to change(CraneComplement, :count).by(1)
      end

      it "redirects to the created crane_complement" do
        post crane_complements_url, params: { crane_complement: valid_attributes }
        expect(response).to redirect_to(crane_complement_url(CraneComplement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CraneComplement" do
        expect {
          post crane_complements_url, params: { crane_complement: invalid_attributes }
        }.to change(CraneComplement, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post crane_complements_url, params: { crane_complement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested crane_complement" do
        crane_complement = CraneComplement.create! valid_attributes
        patch crane_complement_url(crane_complement), params: { crane_complement: new_attributes }
        crane_complement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the crane_complement" do
        crane_complement = CraneComplement.create! valid_attributes
        patch crane_complement_url(crane_complement), params: { crane_complement: new_attributes }
        crane_complement.reload
        expect(response).to redirect_to(crane_complement_url(crane_complement))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        crane_complement = CraneComplement.create! valid_attributes
        patch crane_complement_url(crane_complement), params: { crane_complement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested crane_complement" do
      crane_complement = CraneComplement.create! valid_attributes
      expect {
        delete crane_complement_url(crane_complement)
      }.to change(CraneComplement, :count).by(-1)
    end

    it "redirects to the crane_complements list" do
      crane_complement = CraneComplement.create! valid_attributes
      delete crane_complement_url(crane_complement)
      expect(response).to redirect_to(crane_complements_url)
    end
  end
end
