require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/line_item_materials", type: :request do
  let(:user) { create(:user) }
  let(:section_category) { SectionCategory.create!(name: "Test Category", display_name: "Test Category") }
  let(:tender) { Tender.create!(tender_name: "Test Tender", status: "Draft") }
  let(:tender_line_item) { TenderLineItem.create!(tender: tender, quantity: 1, rate: 0, section_category: section_category) }
  let(:line_item_material_breakdown) { tender_line_item.line_item_material_breakdown }
  let(:line_item_material) { LineItemMaterial.create!(line_item_material_breakdown: line_item_material_breakdown, rate: 100, proportion_percentage: 100) }
  
  let(:valid_attributes) {
    { rate: 150 }
  }

  let(:invalid_attributes) {
    { rate: -10 }
  }

  before { sign_in(user) }

  describe "PATCH /update" do
    context "with valid parameters" do
      it "updates the requested line_item_material and returns turbo streams" do
        patch line_item_material_url(line_item_material), params: { line_item_material: valid_attributes }, as: :turbo_stream
        
        expect(response).to have_http_status(:ok)
        expect(response.body).to include("turbo-stream")
        expect(response.body).to include("target=\"line_item_material_#{line_item_material.id}\"")
        expect(response.body).to include("target=\"material_breakdown_totals_#{line_item_material_breakdown.id}\"")
        expect(response.body).to include("target=\"line_item_rate_build_up_#{tender_line_item.line_item_rate_build_up.id}\"")
        
        line_item_material.reload
        expect(line_item_material.rate).to eq(150)
      end
    end
  end
end
