require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/line_item_material_templates", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # LineItemMaterialTemplate. As you add validations to LineItemMaterialTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LineItemMaterialTemplate.create! valid_attributes
      get line_item_material_templates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
      get line_item_material_template_url(line_item_material_template)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_line_item_material_template_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
      get edit_line_item_material_template_url(line_item_material_template)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LineItemMaterialTemplate" do
        expect {
          post line_item_material_templates_url, params: { line_item_material_template: valid_attributes }
        }.to change(LineItemMaterialTemplate, :count).by(1)
      end

      it "redirects to the created line_item_material_template" do
        post line_item_material_templates_url, params: { line_item_material_template: valid_attributes }
        expect(response).to redirect_to(line_item_material_template_url(LineItemMaterialTemplate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LineItemMaterialTemplate" do
        expect {
          post line_item_material_templates_url, params: { line_item_material_template: invalid_attributes }
        }.to change(LineItemMaterialTemplate, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post line_item_material_templates_url, params: { line_item_material_template: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested line_item_material_template" do
        line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
        patch line_item_material_template_url(line_item_material_template), params: { line_item_material_template: new_attributes }
        line_item_material_template.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the line_item_material_template" do
        line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
        patch line_item_material_template_url(line_item_material_template), params: { line_item_material_template: new_attributes }
        line_item_material_template.reload
        expect(response).to redirect_to(line_item_material_template_url(line_item_material_template))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
        patch line_item_material_template_url(line_item_material_template), params: { line_item_material_template: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested line_item_material_template" do
      line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
      expect {
        delete line_item_material_template_url(line_item_material_template)
      }.to change(LineItemMaterialTemplate, :count).by(-1)
    end

    it "redirects to the line_item_material_templates list" do
      line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
      delete line_item_material_template_url(line_item_material_template)
      expect(response).to redirect_to(line_item_material_templates_url)
    end
  end
end
