require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/line_item_material_templates", type: :request do
  include Devise::Test::IntegrationHelpers

  let(:user) { User.create!(email: "test@example.com", password: "password", role: "admin") }
  before { sign_in user }

  let(:section_category) { SectionCategory.create!(name: "Test Category", display_name: "Test Category") }
  let(:section_category_template) { SectionCategoryTemplate.create!(section_category: section_category) }
  let(:material_supply) { MaterialSupply.create!(name: "Test Material", waste_percentage: 5.0) }

  let(:valid_attributes) {
    {
      section_category_template_id: section_category_template.id,
      material_supply_id: material_supply.id,
      proportion_percentage: 50.0,
      waste_percentage: 5.0,
      sort_order: 1
    }
  }

  let(:invalid_attributes) {
    {
      proportion_percentage: 150.0
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      LineItemMaterialTemplate.create! valid_attributes
      get line_item_material_templates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
      get line_item_material_template_url(line_item_material_template)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_line_item_material_template_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
      get edit_line_item_material_template_url(line_item_material_template)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LineItemMaterialTemplate" do
        expect {
          post line_item_material_templates_url, params: { line_item_material_template: valid_attributes }
        }.to change(LineItemMaterialTemplate, :count).by(1)
      end

      it "redirects to the created line_item_material_template" do
        post line_item_material_templates_url, params: { line_item_material_template: valid_attributes }
        expect(response).to redirect_to(line_item_material_template_url(LineItemMaterialTemplate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LineItemMaterialTemplate" do
        expect {
          post line_item_material_templates_url, params: { line_item_material_template: invalid_attributes }
        }.to change(LineItemMaterialTemplate, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post line_item_material_templates_url, params: { line_item_material_template: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with Turbo Stream" do
      it "returns a turbo stream response when updated via turbo" do
        line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
        patch line_item_material_template_url(line_item_material_template), 
              params: { line_item_material_template: { proportion_percentage: 60.0 } },
              as: :turbo_stream
        
        expect(response).to have_http_status(:ok)
        expect(response.body).to include("turbo-stream")
        expect(response.body).to include("replace")
        expect(response.body).to include("line_item_material_template_#{line_item_material_template.id}")
      end
    end

    context "with valid parameters" do
      let(:new_attributes) {
        { proportion_percentage: 75.0 }
      }

      it "updates the requested line_item_material_template" do
        line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
        patch line_item_material_template_url(line_item_material_template), params: { line_item_material_template: new_attributes }
        line_item_material_template.reload
        expect(line_item_material_template.proportion_percentage).to eq(75.0)
      end

      it "redirects to the line_item_material_template" do
        line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
        patch line_item_material_template_url(line_item_material_template), params: { line_item_material_template: new_attributes }
        line_item_material_template.reload
        expect(response).to redirect_to(line_item_material_template_url(line_item_material_template))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
        patch line_item_material_template_url(line_item_material_template), params: { line_item_material_template: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested line_item_material_template" do
      line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
      expect {
        delete line_item_material_template_url(line_item_material_template)
      }.to change(LineItemMaterialTemplate, :count).by(-1)
    end

    it "redirects to the section_category_template" do
      line_item_material_template = LineItemMaterialTemplate.create! valid_attributes
      delete line_item_material_template_url(line_item_material_template)
      expect(response).to redirect_to(section_category_template_path(section_category_template))
    end
  end
end
