require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/line_item_material_breakdowns", type: :request do
  let(:user) { create(:user) }
  
  # This should return the minimal set of attributes required to create a valid
  # LineItemMaterialBreakdown. As you add validations to LineItemMaterialBreakdown, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  before { sign_in(user) }

  describe "GET /index" do
    it "renders a successful response" do
      LineItemMaterialBreakdown.create! valid_attributes
      get line_item_material_breakdowns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      line_item_material_breakdown = LineItemMaterialBreakdown.create! valid_attributes
      get line_item_material_breakdown_url(line_item_material_breakdown)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_line_item_material_breakdown_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      line_item_material_breakdown = LineItemMaterialBreakdown.create! valid_attributes
      get edit_line_item_material_breakdown_url(line_item_material_breakdown)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LineItemMaterialBreakdown" do
        expect {
          post line_item_material_breakdowns_url, params: { line_item_material_breakdown: valid_attributes }
        }.to change(LineItemMaterialBreakdown, :count).by(1)
      end

      it "redirects to the created line_item_material_breakdown" do
        post line_item_material_breakdowns_url, params: { line_item_material_breakdown: valid_attributes }
        expect(response).to redirect_to(line_item_material_breakdown_url(LineItemMaterialBreakdown.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LineItemMaterialBreakdown" do
        expect {
          post line_item_material_breakdowns_url, params: { line_item_material_breakdown: invalid_attributes }
        }.to change(LineItemMaterialBreakdown, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post line_item_material_breakdowns_url, params: { line_item_material_breakdown: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    let(:tender) { create(:tender) }
    let(:tender_line_item) { create(:tender_line_item, tender: tender) }
    let(:breakdown) { create(:line_item_material_breakdown, tender_line_item: tender_line_item) }
    let!(:rate_buildup) { create(:line_item_rate_build_up, tender_line_item: tender_line_item) }

    context "with valid parameters" do
      it "updates the rounding_interval and syncs to rate buildup" do
        patch line_item_material_breakdown_url(breakdown), 
              params: { line_item_material_breakdown: { rounding_interval: 100 } },
              as: :turbo_stream
        
        breakdown.reload
        expect(breakdown.rounding_interval).to eq(100)
        expect(rate_buildup.reload.material_supply_rate).to eq(breakdown.total)
      end

      it "updates the margin_percentage and syncs to rate buildup" do
        patch line_item_material_breakdown_url(breakdown), 
              params: { line_item_material_breakdown: { margin_percentage: 15 } },
              as: :turbo_stream
        
        breakdown.reload
        expect(breakdown.margin_percentage).to eq(15)
        expect(rate_buildup.reload.material_supply_rate).to eq(breakdown.total)
      end
    end
  end

  describe "PATCH /update_section_category" do
    let(:tender) { create(:tender) }
    let(:tender_line_item) { create(:tender_line_item, tender: tender) }
    let(:breakdown) { create(:line_item_material_breakdown, tender_line_item: tender_line_item) }
    let(:section_category) { create(:section_category, display_name: "Steel Sections") }
    let(:material_supply) { create(:material_supply, name: "Structural Steel", waste_percentage: 5.0) }
    let!(:template) { create(:section_category_template, section_category: section_category) }
    let!(:material_template) do
      create(:line_item_material_template, 
        section_category_template: template, 
        material_supply: material_supply,
        proportion_percentage: 100.0,
        waste_percentage: 10.0
      )
    end
    let!(:tender_rate) do
      rate = tender.tender_specific_material_rates.find_or_initialize_by(material_supply: material_supply)
      rate.update!(rate: 1500.0, unit: "tonne")
      rate
    end

    it "updates the tender line item's section category" do
      patch update_section_category_line_item_material_breakdown_path(breakdown), 
            params: { section_category_id: section_category.id },
            as: :turbo_stream

      expect(tender_line_item.reload.section_category_id).to eq(section_category.id)
    end

    it "populates the breakdown with materials from the template" do
      expect {
        patch update_section_category_line_item_material_breakdown_path(breakdown), 
              params: { section_category_id: section_category.id },
              as: :turbo_stream
      }.to change(LineItemMaterial, :count).by(1)

      material = LineItemMaterial.last
      expect(material.material_supply).to eq(material_supply)
      expect(material.proportion_percentage).to eq(100.0)
      expect(material.waste_percentage).to eq(10.0)
      expect(material.rate).to eq(1500.0)
    end

    it "responds with turbo stream" do
      patch update_section_category_line_item_material_breakdown_path(breakdown), 
            params: { section_category_id: section_category.id },
            as: :turbo_stream

      expect(response.content_type).to include("text/vnd.turbo-stream.html")
      expect(response.body).to include("turbo-stream action=\"replace\" target=\"line_item_material_breakdown_#{breakdown.id}\"")
    end

    context "when selecting the same category" do
      before do
        tender_line_item.update!(section_category_id: section_category.id)
      end

      it "does not populate materials again" do
        expect {
          patch update_section_category_line_item_material_breakdown_path(breakdown), 
                params: { section_category_id: section_category.id },
                as: :turbo_stream
        }.not_to change(LineItemMaterial, :count)
      end
    end
  end
end
