require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/line_item_rate_build_ups", type: :request do
  let(:user) { create(:user) }
  
  # This should return the minimal set of attributes required to create a valid
  # LineItemRateBuildUp. As you add validations to LineItemRateBuildUp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  before { sign_in(user) }

  describe "GET /index" do
    it "renders a successful response" do
      LineItemRateBuildUp.create! valid_attributes
      get line_item_rate_build_ups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      line_item_rate_build_up = LineItemRateBuildUp.create! valid_attributes
      get line_item_rate_build_up_url(line_item_rate_build_up)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_line_item_rate_build_up_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      line_item_rate_build_up = LineItemRateBuildUp.create! valid_attributes
      get edit_line_item_rate_build_up_url(line_item_rate_build_up)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LineItemRateBuildUp" do
        expect {
          post line_item_rate_build_ups_url, params: { line_item_rate_build_up: valid_attributes }
        }.to change(LineItemRateBuildUp, :count).by(1)
      end

      it "redirects to the created line_item_rate_build_up" do
        post line_item_rate_build_ups_url, params: { line_item_rate_build_up: valid_attributes }
        expect(response).to redirect_to(line_item_rate_build_up_url(LineItemRateBuildUp.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LineItemRateBuildUp" do
        expect {
          post line_item_rate_build_ups_url, params: { line_item_rate_build_up: invalid_attributes }
        }.to change(LineItemRateBuildUp, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post line_item_rate_build_ups_url, params: { line_item_rate_build_up: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested line_item_rate_build_up" do
        line_item_rate_build_up = LineItemRateBuildUp.create! valid_attributes
        patch line_item_rate_build_up_url(line_item_rate_build_up), params: { line_item_rate_build_up: new_attributes }
        line_item_rate_build_up.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the line_item_rate_build_up" do
        line_item_rate_build_up = LineItemRateBuildUp.create! valid_attributes
        patch line_item_rate_build_up_url(line_item_rate_build_up), params: { line_item_rate_build_up: new_attributes }
        line_item_rate_build_up.reload
        expect(response).to redirect_to(line_item_rate_build_up_url(line_item_rate_build_up))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        line_item_rate_build_up = LineItemRateBuildUp.create! valid_attributes
        patch line_item_rate_build_up_url(line_item_rate_build_up), params: { line_item_rate_build_up: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested line_item_rate_build_up" do
      line_item_rate_build_up = LineItemRateBuildUp.create! valid_attributes
      expect {
        delete line_item_rate_build_up_url(line_item_rate_build_up)
      }.to change(LineItemRateBuildUp, :count).by(-1)
    end

    it "redirects to the line_item_rate_build_ups list" do
      line_item_rate_build_up = LineItemRateBuildUp.create! valid_attributes
      delete line_item_rate_build_up_url(line_item_rate_build_up)
      expect(response).to redirect_to(line_item_rate_build_ups_url)
    end
  end
end
