require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/material_supplies", type: :request do
  let(:user) { create(:user) }
  
  # This should return the minimal set of attributes required to create a valid
  # MaterialSupply. As you add validations to MaterialSupply, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Material A", waste_percentage: 5.0 }
  }

  let(:invalid_attributes) {
    { name: "", waste_percentage: -1.0 }
  }

  before { sign_in(user) }

  describe "PATCH /reorder" do
    it "reorders the materials" do
      m1 = MaterialSupply.create!(name: "M1", waste_percentage: 5, position: 1)
      m2 = MaterialSupply.create!(name: "M2", waste_percentage: 5, position: 2)
      
      patch reorder_material_supplies_path, params: { ids: [m2.id, m1.id] }
      
      expect(response).to have_http_status(:ok)
      expect(m2.reload.position).to eq(1)
      expect(m1.reload.position).to eq(2)
    end
  end

  describe "GET /index" do
    it "renders a successful response" do
      MaterialSupply.create! valid_attributes
      get material_supplies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      material_supply = MaterialSupply.create! valid_attributes
      get material_supply_url(material_supply)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_material_supply_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      material_supply = MaterialSupply.create! valid_attributes
      get edit_material_supply_url(material_supply)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MaterialSupply" do
        expect {
          post material_supplies_url, params: { material_supply: valid_attributes }
        }.to change(MaterialSupply, :count).by(1)
      end

      it "redirects to the created material_supply" do
        post material_supplies_url, params: { material_supply: valid_attributes }
        expect(response).to redirect_to(material_supply_url(MaterialSupply.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MaterialSupply" do
        expect {
          post material_supplies_url, params: { material_supply: invalid_attributes }
        }.to change(MaterialSupply, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post material_supplies_url, params: { material_supply: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested material_supply" do
        material_supply = MaterialSupply.create! valid_attributes
        patch material_supply_url(material_supply), params: { material_supply: new_attributes }
        material_supply.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the material_supply" do
        material_supply = MaterialSupply.create! valid_attributes
        patch material_supply_url(material_supply), params: { material_supply: new_attributes }
        material_supply.reload
        expect(response).to redirect_to(material_supply_url(material_supply))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        material_supply = MaterialSupply.create! valid_attributes
        patch material_supply_url(material_supply), params: { material_supply: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested material_supply" do
      material_supply = MaterialSupply.create! valid_attributes
      expect {
        delete material_supply_url(material_supply)
      }.to change(MaterialSupply, :count).by(-1)
    end

    it "redirects to the material_supplies list" do
      material_supply = MaterialSupply.create! valid_attributes
      delete material_supply_url(material_supply)
      expect(response).to redirect_to(material_supplies_url)
    end
  end
end
