require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/on_site_mobile_crane_breakdowns", type: :request do
  let(:user) { create(:user) }
  
  # This should return the minimal wset of attributes required to create a valid
  # OnSiteMobileCraneBreakdown. As you add validations to OnSiteMobileCraneBreakdown, be sure to
  # adjust the attributes here as well.
  let(:tender) { create(:tender) }

  let(:valid_attributes) {
    {
      tender_id: tender.id,
      total_roof_area_sqm: 1000.0,
      erection_rate_sqm_per_day: 50.0,
      program_duration_days: 20,
      ownership_type: "rental",
      splicing_crane_required: false,
      misc_crane_required: false
    }
  }

  let(:invalid_attributes) {
    { tender_id: nil }
  }

  before { sign_in(user) }

  describe "GET /index" do
    it "renders a successful response" do
      OnSiteMobileCraneBreakdown.create! valid_attributes
      get on_site_mobile_crane_breakdowns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
      get on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_on_site_mobile_crane_breakdown_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
      get edit_on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OnSiteMobileCraneBreakdown" do
        expect {
          post on_site_mobile_crane_breakdowns_url, params: { on_site_mobile_crane_breakdown: valid_attributes }
        }.to change(OnSiteMobileCraneBreakdown, :count).by(1)
      end

      it "redirects to the created on_site_mobile_crane_breakdown" do
        post on_site_mobile_crane_breakdowns_url, params: { on_site_mobile_crane_breakdown: valid_attributes }
        expect(response).to redirect_to(on_site_mobile_crane_breakdown_url(OnSiteMobileCraneBreakdown.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OnSiteMobileCraneBreakdown" do
        expect {
          post on_site_mobile_crane_breakdowns_url, params: { on_site_mobile_crane_breakdown: invalid_attributes }
        }.to change(OnSiteMobileCraneBreakdown, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post on_site_mobile_crane_breakdowns_url, params: { on_site_mobile_crane_breakdown: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          total_roof_area_sqm: 2000.0,
          erection_rate_sqm_per_day: 80.0
        }
      }

      it "updates the requested on_site_mobile_crane_breakdown" do
        on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
        patch on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown), params: { on_site_mobile_crane_breakdown: new_attributes }
        on_site_mobile_crane_breakdown.reload
        expect(on_site_mobile_crane_breakdown.total_roof_area_sqm).to eq(2000.0)
        expect(on_site_mobile_crane_breakdown.erection_rate_sqm_per_day).to eq(80.0)
      end

      it "redirects to the on_site_mobile_crane_breakdown" do
        on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
        patch on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown), params: { on_site_mobile_crane_breakdown: new_attributes }
        on_site_mobile_crane_breakdown.reload
        expect(response).to redirect_to(on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown))
      end

      it "auto-calculates program_duration_days based on roof area and erection rate" do
        on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
        # Update with 2000 sqm / 80 sqm per day = 25 days
        patch on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown), params: { on_site_mobile_crane_breakdown: new_attributes }
        on_site_mobile_crane_breakdown.reload
        expect(on_site_mobile_crane_breakdown.program_duration_days).to eq(25)
      end

      it "returns turbo_stream response when requested" do
        on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
        patch on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown),
              params: { on_site_mobile_crane_breakdown: new_attributes },
              headers: { "Accept" => "text/vnd.turbo-stream.html" }
        expect(response.media_type).to eq("text/vnd.turbo-stream.html")
        expect(response.body).to include("turbo-stream")
        expect(response.body).to include("replace")
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
        patch on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown), params: { on_site_mobile_crane_breakdown: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested on_site_mobile_crane_breakdown" do
      on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
      expect {
        delete on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown)
      }.to change(OnSiteMobileCraneBreakdown, :count).by(-1)
    end

    it "redirects to the on_site_mobile_crane_breakdowns list" do
      on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
      delete on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown)
      expect(response).to redirect_to(on_site_mobile_crane_breakdowns_url)
    end
  end
end
