require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/on_site_mobile_crane_breakdowns", type: :request do
  let(:user) { create(:user) }
  
  # This should return the minimal set of attributes required to create a valid
  # OnSiteMobileCraneBreakdown. As you add validations to OnSiteMobileCraneBreakdown, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  before { sign_in(user) }

  describe "GET /index" do
    it "renders a successful response" do
      OnSiteMobileCraneBreakdown.create! valid_attributes
      get on_site_mobile_crane_breakdowns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
      get on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_on_site_mobile_crane_breakdown_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
      get edit_on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OnSiteMobileCraneBreakdown" do
        expect {
          post on_site_mobile_crane_breakdowns_url, params: { on_site_mobile_crane_breakdown: valid_attributes }
        }.to change(OnSiteMobileCraneBreakdown, :count).by(1)
      end

      it "redirects to the created on_site_mobile_crane_breakdown" do
        post on_site_mobile_crane_breakdowns_url, params: { on_site_mobile_crane_breakdown: valid_attributes }
        expect(response).to redirect_to(on_site_mobile_crane_breakdown_url(OnSiteMobileCraneBreakdown.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OnSiteMobileCraneBreakdown" do
        expect {
          post on_site_mobile_crane_breakdowns_url, params: { on_site_mobile_crane_breakdown: invalid_attributes }
        }.to change(OnSiteMobileCraneBreakdown, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post on_site_mobile_crane_breakdowns_url, params: { on_site_mobile_crane_breakdown: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested on_site_mobile_crane_breakdown" do
        on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
        patch on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown), params: { on_site_mobile_crane_breakdown: new_attributes }
        on_site_mobile_crane_breakdown.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the on_site_mobile_crane_breakdown" do
        on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
        patch on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown), params: { on_site_mobile_crane_breakdown: new_attributes }
        on_site_mobile_crane_breakdown.reload
        expect(response).to redirect_to(on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
        patch on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown), params: { on_site_mobile_crane_breakdown: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested on_site_mobile_crane_breakdown" do
      on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
      expect {
        delete on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown)
      }.to change(OnSiteMobileCraneBreakdown, :count).by(-1)
    end

    it "redirects to the on_site_mobile_crane_breakdowns list" do
      on_site_mobile_crane_breakdown = OnSiteMobileCraneBreakdown.create! valid_attributes
      delete on_site_mobile_crane_breakdown_url(on_site_mobile_crane_breakdown)
      expect(response).to redirect_to(on_site_mobile_crane_breakdowns_url)
    end
  end
end
