require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/project_rate_build_ups", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProjectRateBuildUp. As you add validations to ProjectRateBuildUp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProjectRateBuildUp.create! valid_attributes
      get project_rate_build_ups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      project_rate_build_up = ProjectRateBuildUp.create! valid_attributes
      get project_rate_build_up_url(project_rate_build_up)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_project_rate_build_up_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      project_rate_build_up = ProjectRateBuildUp.create! valid_attributes
      get edit_project_rate_build_up_url(project_rate_build_up)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProjectRateBuildUp" do
        expect {
          post project_rate_build_ups_url, params: { project_rate_build_up: valid_attributes }
        }.to change(ProjectRateBuildUp, :count).by(1)
      end

      it "redirects to the created project_rate_build_up" do
        post project_rate_build_ups_url, params: { project_rate_build_up: valid_attributes }
        expect(response).to redirect_to(project_rate_build_up_url(ProjectRateBuildUp.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProjectRateBuildUp" do
        expect {
          post project_rate_build_ups_url, params: { project_rate_build_up: invalid_attributes }
        }.to change(ProjectRateBuildUp, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post project_rate_build_ups_url, params: { project_rate_build_up: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project_rate_build_up" do
        project_rate_build_up = ProjectRateBuildUp.create! valid_attributes
        patch project_rate_build_up_url(project_rate_build_up), params: { project_rate_build_up: new_attributes }
        project_rate_build_up.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the project_rate_build_up" do
        project_rate_build_up = ProjectRateBuildUp.create! valid_attributes
        patch project_rate_build_up_url(project_rate_build_up), params: { project_rate_build_up: new_attributes }
        project_rate_build_up.reload
        expect(response).to redirect_to(project_rate_build_up_url(project_rate_build_up))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        project_rate_build_up = ProjectRateBuildUp.create! valid_attributes
        patch project_rate_build_up_url(project_rate_build_up), params: { project_rate_build_up: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested project_rate_build_up" do
      project_rate_build_up = ProjectRateBuildUp.create! valid_attributes
      expect {
        delete project_rate_build_up_url(project_rate_build_up)
      }.to change(ProjectRateBuildUp, :count).by(-1)
    end

    it "redirects to the project_rate_build_ups list" do
      project_rate_build_up = ProjectRateBuildUp.create! valid_attributes
      delete project_rate_build_up_url(project_rate_build_up)
      expect(response).to redirect_to(project_rate_build_ups_url)
    end
  end
end
