require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/section_category_templates", type: :request do
  let(:user) { create(:user) }
  before { sign_in user }

  let(:section_category) { SectionCategory.create!(name: "test_cat", display_name: "Test Cat") }
  let(:valid_attributes) {
    { section_category_id: section_category.id }
  }

  let(:invalid_attributes) {
    { section_category_id: nil }
  }

  describe "POST /bulk_create_slots" do
    it "creates 4 material slots" do
      section_category_template = SectionCategoryTemplate.create! valid_attributes
      expect {
        post bulk_create_slots_section_category_template_url(section_category_template)
      }.to change(LineItemMaterialTemplate, :count).by(4)
      expect(response).to redirect_to(section_category_template_url(section_category_template))
      expect(flash[:notice]).to eq("4 default material slots were successfully created.")
    end
  end

  describe "GET /index" do
    it "renders a successful response" do
      SectionCategoryTemplate.create! valid_attributes
      get section_category_templates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      section_category_template = SectionCategoryTemplate.create! valid_attributes
      get section_category_template_url(section_category_template)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_section_category_template_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      section_category_template = SectionCategoryTemplate.create! valid_attributes
      get edit_section_category_template_url(section_category_template)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SectionCategoryTemplate" do
        expect {
          post section_category_templates_url, params: { section_category_template: valid_attributes }
        }.to change(SectionCategoryTemplate, :count).by(1)
      end

      it "redirects to the created section_category_template" do
        post section_category_templates_url, params: { section_category_template: valid_attributes }
        expect(response).to redirect_to(section_category_template_url(SectionCategoryTemplate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SectionCategoryTemplate" do
        expect {
          post section_category_templates_url, params: { section_category_template: invalid_attributes }
        }.to change(SectionCategoryTemplate, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post section_category_templates_url, params: { section_category_template: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      it "updates the requested section_category_template" do
        section_category_template = SectionCategoryTemplate.create! valid_attributes
        new_category = SectionCategory.create!(name: "new_cat", display_name: "New Cat")
        patch section_category_template_url(section_category_template), params: { section_category_template: { section_category_id: new_category.id } }
        section_category_template.reload
        expect(section_category_template.section_category_id).to eq(new_category.id)
      end

      it "redirects to the section_category_template" do
        section_category_template = SectionCategoryTemplate.create! valid_attributes
        patch section_category_template_url(section_category_template), params: { section_category_template: valid_attributes }
        section_category_template.reload
        expect(response).to redirect_to(section_category_template_url(section_category_template))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        section_category_template = SectionCategoryTemplate.create! valid_attributes
        patch section_category_template_url(section_category_template), params: { section_category_template: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested section_category_template" do
      section_category_template = SectionCategoryTemplate.create! valid_attributes
      expect {
        delete section_category_template_url(section_category_template)
      }.to change(SectionCategoryTemplate, :count).by(-1)
    end

    it "redirects to the section_category_templates list" do
      section_category_template = SectionCategoryTemplate.create! valid_attributes
      delete section_category_template_url(section_category_template)
      expect(response).to redirect_to(section_category_templates_url)
    end
  end
end
