require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tenders", type: :request do
  let(:user) { create(:user) }
  
  # This should return the minimal set of attributes required to create a valid
  # Tender. As you add validations to Tender, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      tender_name: "Test Tender",
      status: "Draft"
    }
  }

  let(:invalid_attributes) {
    {
      tender_name: "",
      status: "Invalid Status"
    }
  }

  before { sign_in(user) }

  describe "GET /report" do
    let(:tender) { Tender.create! valid_attributes }

    it "renders a successful HTML response" do
      get report_tender_url(tender)
      expect(response).to be_successful
    end

    it "returns a successful PDF response" do
      # Grover might need a running browser or mock, but let's see if it works in the test env
      get report_tender_url(tender, format: :pdf)
      expect(response).to be_successful
      expect(response.content_type).to eq('application/pdf')
      # Rails encodes the filename in Content-Disposition header according to RFC 6266
      # It provides both a 'filename' (often with substitutions for non-ASCII) and 'filename*' (properly encoded)
      content_disposition = response.headers['Content-Disposition']
      expect(content_disposition).to include("filename*=")
      expect(content_disposition).to include("E2026001")
      expect(content_disposition).to include("Test%20Tender")
      # %E2%80%93 is the URL-encoded en dash
      expect(content_disposition).to include("%E2%80%93")
      expect(response.body).not_to be_empty
    end

    context "report display customization" do
      let!(:pg_item) { create(:preliminaries_general_item, tender: tender, description: "Detailed P&G Item", quantity: 1, rate: 1000) }
      
      before do
        tender.reload
        tender.project_rate_buildup.update!(shop_drawings_rate: 500, shop_drawings_tonnes: 10)
        tender.recalculate_grand_total!
      end

      it "renders P&G breakdown when mode is detailed" do
        tender.update!(p_and_g_display_mode: 'detailed')
        get report_tender_url(tender)
        expect(response.body).to include("Detailed P&amp;G Item")
        expect(response.body).not_to include("Preliminaries & Generals (Rolled-up)")
      end

      it "renders single P&G row when mode is rolled_up" do
        tender.update!(p_and_g_display_mode: 'rolled_up')
        get report_tender_url(tender)
        expect(response.body).to include("Preliminaries & Generals (Rolled-up)")
        expect(response.body).not_to include("Detailed P&amp;G Item")
      end

      it "renders Shop Drawings tonnage/rate when mode is tonnage_rate" do
        tender.update!(shop_drawings_display_mode: 'tonnage_rate')
        get report_tender_url(tender)
        expect(response.body).to include("10.00")
        expect(response.body).to include("500.0")
      end

      it "renders Shop Drawings as lump sum when mode is lump_sum" do
        tender.update!(shop_drawings_display_mode: 'lump_sum')
        get report_tender_url(tender)
        expect(response.body).to include("Sum")
        expect(response.body).to include("1.00")
        expect(response.body).to include("5,000.0") # 10 * 500
      end
    end

    context "updating display modes from report" do
      let!(:pg_item) { create(:preliminaries_general_item, tender: tender, description: "Test P&G", quantity: 1, rate: 100) }
      
      it "successfully updates and renders report content for turbo_stream" do
        patch tender_url(tender), params: { 
          source: 'report', 
          tender: { p_and_g_display_mode: 'rolled_up' } 
        }, as: :turbo_stream
        
        expect(response).to be_successful
        expect(response.body).to include("Preliminaries & Generals (Rolled-up)")
      end

      it "successfully updates and renders report content for html" do
        patch tender_url(tender), params: { 
          source: 'report', 
          tender: { p_and_g_display_mode: 'rolled_up' } 
        }
        
        expect(response).to be_successful
        expect(response.body).to include("Preliminaries & Generals (Rolled-up)")
      end
    end
  end

  describe "GET /index" do
    it "renders a successful response" do
      Tender.create! valid_attributes
      get tenders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tender = Tender.create! valid_attributes
      get tender_url(tender)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tender_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tender = Tender.create! valid_attributes
      get edit_tender_url(tender)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tender" do
        expect {
          post tenders_url, params: { tender: valid_attributes }
        }.to change(Tender, :count).by(1)
      end

      it "redirects to the created tender" do
        post tenders_url, params: { tender: valid_attributes }
        expect(response).to redirect_to(tender_url(Tender.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tender" do
        expect {
          post tenders_url, params: { tender: invalid_attributes }
        }.to change(Tender, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post tenders_url, params: { tender: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tender" do
        tender = Tender.create! valid_attributes
        patch tender_url(tender), params: { tender: new_attributes }
        tender.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tender" do
        tender = Tender.create! valid_attributes
        patch tender_url(tender), params: { tender: new_attributes }
        tender.reload
        expect(response).to redirect_to(tender_url(tender))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        tender = Tender.create! valid_attributes
        patch tender_url(tender), params: { tender: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tender" do
      tender = Tender.create! valid_attributes
      expect {
        delete tender_url(tender)
      }.to change(Tender, :count).by(-1)
    end

    it "redirects to the tenders list" do
      tender = Tender.create! valid_attributes
      delete tender_url(tender)
      expect(response).to redirect_to(tenders_url)
    end
  end
end
