require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tenders", type: :request do
  let(:user) { create(:user, :admin) }
  
  # This should return the minimal set of attributes required to create a valid
  # Tender. As you add validations to Tender, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      tender_name: "Test Tender",
      status: "Draft"
    }
  }

  let(:invalid_attributes) {
    {
      tender_name: "",
      status: "Invalid Status"
    }
  }

  before { sign_in(user) }

  describe "GET /report" do
    let(:tender) { Tender.create! valid_attributes }

    it "renders a successful HTML response" do
      get report_tender_url(tender)
      expect(response).to be_successful
    end

    it "returns a successful PDF response" do
      # Grover might need a running browser or mock, but let's see if it works in the test env
      get report_tender_url(tender, format: :pdf)
      expect(response).to be_successful
      expect(response.content_type).to eq('application/pdf')
      # Rails encodes the filename in Content-Disposition header according to RFC 6266
      # It provides both a 'filename' (often with substitutions for non-ASCII) and 'filename*' (properly encoded)
      content_disposition = response.headers['Content-Disposition']
      expect(content_disposition).to include("filename*=")
      expect(content_disposition).to include("E2026001")
      expect(content_disposition).to include("Test%20Tender")
      # %E2%80%93 is the URL-encoded en dash
      expect(content_disposition).to include("%E2%80%93")
      expect(response.body).not_to be_empty
    end

    context "report display customization" do
      let!(:pg_item) { create(:preliminaries_general_item, tender: tender, description: "Detailed P&G Item", quantity: 1, rate: 1000) }
      
      before do
        tender.reload
        tender.project_rate_buildup.update!(shop_drawings_rate: 500, shop_drawings_tonnes: 10)
        tender.recalculate_grand_total!
      end

      it "renders P&G breakdown when mode is detailed" do
        tender.update!(p_and_g_display_mode: 'detailed')
        get report_tender_url(tender)
        expect(response.body).to include("Detailed P&amp;G Item")
        expect(response.body).not_to include("Preliminaries & Generals (Rolled-up)")
      end

      it "renders single P&G row when mode is rolled_up" do
        tender.update!(p_and_g_display_mode: 'rolled_up')
        get report_tender_url(tender)
        expect(response.body).to include("Preliminaries & Generals (Rolled-up)")
        expect(response.body).not_to include("Detailed P&amp;G Item")
      end

      it "renders Shop Drawings tonnage/rate when mode is tonnage_rate" do
        tender.update!(shop_drawings_display_mode: 'tonnage_rate')
        get report_tender_url(tender)
        expect(response.body).to include("10.00")
        expect(response.body).to include("500.0")
      end

      it "renders Shop Drawings as lump sum when mode is lump_sum" do
        tender.update!(shop_drawings_display_mode: 'lump_sum')
        get report_tender_url(tender)
        expect(response.body).to include("Sum")
        expect(response.body).to include("1.00")
        expect(response.body).to include("5,000.0") # 10 * 500
      end
    end

    context "updating display modes from report" do
      let!(:pg_item) { create(:preliminaries_general_item, tender: tender, description: "Test P&G", quantity: 1, rate: 100) }
      
      it "successfully updates and renders report content for turbo_stream" do
        patch tender_url(tender), params: { 
          source: 'report', 
          tender: { p_and_g_display_mode: 'rolled_up' } 
        }, as: :turbo_stream
        
        expect(response).to be_successful
        expect(response.body).to include("Preliminaries & Generals (Rolled-up)")
      end

      it "successfully updates and renders report content for html" do
        patch tender_url(tender), params: { 
          source: 'report', 
          tender: { p_and_g_display_mode: 'rolled_up' } 
        }
        
        expect(response).to be_successful
        expect(response.body).to include("Preliminaries & Generals (Rolled-up)")
      end
    end

    context "dynamic expiration date calculation" do
      it "displays expiration date as 30 days from today" do
        get report_tender_url(tender)
        expected_date = (Date.current + 30.days).strftime("%B %d, %Y")
        expect(response.body).to include(expected_date)
      end

      it "updates expiration date on different view dates" do
        # First view
        get report_tender_url(tender)
        today_expiration = (Date.current + 30.days).strftime("%B %d, %Y")
        expect(response.body).to include(today_expiration)

        # Travel to 5 days in the future
        travel_to 5.days.from_now do
          get report_tender_url(tender)
          future_expiration = (Date.current + 30.days).strftime("%B %d, %Y")
          expect(response.body).to include(future_expiration)
          # Verify it's NOT the original expiration date
          expect(future_expiration).not_to eq(today_expiration)
        end
      end

      it "respects submission_deadline priority over 30-day calculation" do
        deadline = Date.current + 15.days
        tender.update!(submission_deadline: deadline)
        
        get report_tender_url(tender)
        expected_date = deadline.strftime("%B %d, %Y")
        expect(response.body).to include(expected_date)
        
        # Verify it does NOT show the 30-day calculation
        thirty_days_from_now = (Date.current + 30.days).strftime("%B %d, %Y")
        expect(response.body).not_to include(thirty_days_from_now)
      end

      it "shows submission_deadline even when viewed on different dates" do
        deadline = Date.current + 15.days
        tender.update!(submission_deadline: deadline)
        expected_date = deadline.strftime("%B %d, %Y")
        
        get report_tender_url(tender)
        expect(response.body).to include(expected_date)
        
        # Travel to 5 days in the future
        travel_to 5.days.from_now do
          get report_tender_url(tender)
          expect(response.body).to include(expected_date)
        end
      end
    end
  end

  describe "GET /index" do
    it "renders a successful response" do
      Tender.create! valid_attributes
      get tenders_url
      expect(response).to be_successful
    end
  end

  describe "Material Buyer access" do
    let(:buyer) { User.create!(email: 'buyer@example.com', password: 'password', role: :material_buyer) }
    before { sign_in(buyer) }

    it "redirects from index" do
      get tenders_url
      expect(response).to redirect_to(root_path)
    end

    it "redirects from show" do
      tender = Tender.create! valid_attributes
      get tender_url(tender)
      expect(response).to redirect_to(root_path)
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tender = Tender.create! valid_attributes
      get tender_url(tender)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tender_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tender = Tender.create! valid_attributes
      get edit_tender_url(tender)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tender" do
        expect {
          post tenders_url, params: { tender: valid_attributes }
        }.to change(Tender, :count).by(1)
      end

      it "redirects to the created tender" do
        post tenders_url, params: { tender: valid_attributes }
        expect(response).to redirect_to(tender_url(Tender.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tender" do
        expect {
          post tenders_url, params: { tender: invalid_attributes }
        }.to change(Tender, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post tenders_url, params: { tender: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tender" do
        tender = Tender.create! valid_attributes
        patch tender_url(tender), params: { tender: new_attributes }
        tender.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tender" do
        tender = Tender.create! valid_attributes
        patch tender_url(tender), params: { tender: new_attributes }
        tender.reload
        expect(response).to redirect_to(tender_url(tender))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        tender = Tender.create! valid_attributes
        patch tender_url(tender), params: { tender: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end

    context "with notes and turbo_stream" do
      it "updates the notes and responds with no_content for background saves" do
        tender = Tender.create! valid_attributes
        patch tender_url(tender), params: { tender: { notes: "Updated note" } }, as: :turbo_stream
        
        expect(response).to have_http_status(:no_content)
        expect(tender.reload.notes).to eq("Updated note")
      end

      it "responds with turbo_stream replacement when updating more than just notes" do
        tender = Tender.create! valid_attributes
        patch tender_url(tender), params: { tender: { notes: "Updated note", status: "Awarded" } }, as: :turbo_stream
        
        expect(response).to be_successful
        expect(response.body).to include("turbo-stream")
        expect(response.body).to include("replace")
        expect(tender.reload.status).to eq("Awarded")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tender" do
      tender = Tender.create! valid_attributes
      expect {
        delete tender_url(tender)
      }.to change(Tender, :count).by(-1)
    end

    it "redirects to the tenders list" do
      tender = Tender.create! valid_attributes
      delete tender_url(tender)
      expect(response).to redirect_to(tenders_url)
    end
  end

  describe "GET /material_autofill" do
    let(:tender) { Tender.create!(valid_attributes) }
    let(:material_supply) { MaterialSupply.create!(name: "Standard Steel", waste_percentage: 10) }
    let(:anchor_rate) { AnchorRate.create!(name: "M16 Anchor", waste_percentage: 5, material_cost: 100) }

    it "returns autofill data for MaterialSupply" do
      get material_autofill_tender_url(tender, material_supply_id: material_supply.id, material_supply_type: "MaterialSupply")
      expect(response).to be_successful
      json = JSON.parse(response.body)
      expect(json["waste_percentage"]).to eq("10.0")
    end

    it "returns autofill data for AnchorRate" do
      get material_autofill_tender_url(tender, material_supply_id: anchor_rate.id, material_supply_type: "AnchorRate")
      expect(response).to be_successful
      json = JSON.parse(response.body)
      expect(json["waste_percentage"]).to eq("5.0")
    end

    it "returns tender-specific rate if it exists" do
      TenderSpecificMaterialRate.create!(
        tender: tender,
        material_supply_id: material_supply.id,
        material_supply_type: "MaterialSupply",
        rate: 15.50
      )
      get material_autofill_tender_url(tender, material_supply_id: material_supply.id, material_supply_type: "MaterialSupply")
      json = JSON.parse(response.body)
      expect(json["rate"]).to eq("15.5")
    end
  end

  describe "POST /mirror_boq_items" do
    let(:tender) { Tender.create! valid_attributes }
    let(:boq) { create(:boq, tender: tender) }
    let!(:section_category) { create(:section_category, display_name: "Steel Sections", name: "steel_sections") }
    let!(:boq_item) { create(:boq_item, boq: boq, quantity: 10, item_description: "Test Item", section_category: :steel_sections) }

    context "when not mirrored yet" do
      it "creates tender line items and sets boq_mirrored to true" do
        expect {
          post mirror_boq_items_tender_url(tender)
        }.to change(TenderLineItem, :count).by(1)
        
        expect(tender.reload.boq_mirrored).to be true
        expect(response).to redirect_to(builder_tender_url(tender))
      end

      it "returns success JSON when requested as json" do
        post mirror_boq_items_tender_url(tender), as: :json
        expect(response).to have_http_status(:created)
        expect(JSON.parse(response.body)["success"]).to be true
      end
    end

    context "when already mirrored" do
      before { tender.update!(boq_mirrored: true) }

      it "returns unprocessable_entity and does not create duplicates" do
        expect {
          post mirror_boq_items_tender_url(tender)
        }.not_to change(TenderLineItem, :count)
        
        expect(response).to have_http_status(:unprocessable_entity)
        expect(JSON.parse(response.body)["error"]).to eq("BOQ has already been mirrored for this tender")
      end
    end
  end
end
