require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tender_equipment_summaries", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TenderEquipmentSummary. As you add validations to TenderEquipmentSummary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TenderEquipmentSummary.create! valid_attributes
      get tender_equipment_summaries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tender_equipment_summary = TenderEquipmentSummary.create! valid_attributes
      get tender_equipment_summary_url(tender_equipment_summary)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tender_equipment_summary_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tender_equipment_summary = TenderEquipmentSummary.create! valid_attributes
      get edit_tender_equipment_summary_url(tender_equipment_summary)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TenderEquipmentSummary" do
        expect {
          post tender_equipment_summaries_url, params: { tender_equipment_summary: valid_attributes }
        }.to change(TenderEquipmentSummary, :count).by(1)
      end

      it "redirects to the created tender_equipment_summary" do
        post tender_equipment_summaries_url, params: { tender_equipment_summary: valid_attributes }
        expect(response).to redirect_to(tender_equipment_summary_url(TenderEquipmentSummary.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TenderEquipmentSummary" do
        expect {
          post tender_equipment_summaries_url, params: { tender_equipment_summary: invalid_attributes }
        }.to change(TenderEquipmentSummary, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post tender_equipment_summaries_url, params: { tender_equipment_summary: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tender_equipment_summary" do
        tender_equipment_summary = TenderEquipmentSummary.create! valid_attributes
        patch tender_equipment_summary_url(tender_equipment_summary), params: { tender_equipment_summary: new_attributes }
        tender_equipment_summary.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tender_equipment_summary" do
        tender_equipment_summary = TenderEquipmentSummary.create! valid_attributes
        patch tender_equipment_summary_url(tender_equipment_summary), params: { tender_equipment_summary: new_attributes }
        tender_equipment_summary.reload
        expect(response).to redirect_to(tender_equipment_summary_url(tender_equipment_summary))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        tender_equipment_summary = TenderEquipmentSummary.create! valid_attributes
        patch tender_equipment_summary_url(tender_equipment_summary), params: { tender_equipment_summary: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tender_equipment_summary" do
      tender_equipment_summary = TenderEquipmentSummary.create! valid_attributes
      expect {
        delete tender_equipment_summary_url(tender_equipment_summary)
      }.to change(TenderEquipmentSummary, :count).by(-1)
    end

    it "redirects to the tender_equipment_summaries list" do
      tender_equipment_summary = TenderEquipmentSummary.create! valid_attributes
      delete tender_equipment_summary_url(tender_equipment_summary)
      expect(response).to redirect_to(tender_equipment_summaries_url)
    end
  end
end
